config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ## Limit routes to only the ones we are using.
  resources :posts, only: %i[index show] do
    ## Reconfigure the nested route to use a more conformed controller
    ## action method, so that we use the Comments controller to gather
    ## comments and not the Post controller via the custom action #comments.
    resources :comments, only: :index
  end

  ## Limit routes to only the ones we are using.
  resources :users, only: :show

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  scope :published, -> { where(published: true) }

  ## I've delegated the user's name to comment here to remove the need
  ## for the call in the view.
  delegate :name, to: :user, prefix: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates_presence_of :title
  validates_presence_of :body

  scope :published, -> { where(published: true) }
  scope :sort_by_newest, -> { order(created_at: :desc) }
  scope :sort_by_oldest, -> { order(created_at: :asc) }

  ## As in the Comment model, I have delegated the User's name to the Post
  ## model to further clean up the view.
  delegate :name, to: :user, prefix: true

  def self.order_by(sort_value)
    if sort_value == 'asc'
      self.sort_by_oldest
    elsif sort_value == 'desc'
      self.sort_by_newest
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def index
    ## Using the #includes method here to reduce number of queries to the
    ## DB. This will only query the DB 3 times to gather the post, its comments,
    ## and the users for those comments.
    @post = Post.includes(comments: :user).find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def index
    ## We have a scope defined in the Post model, so we will use that here.

    ## I have also used the #includes method here to avoid the N+1 problem,
    ## taking the number of queries for this action to just 2 instead of
    ## the hundreds it was before.
    @posts = Post.published.includes(:user)

    ## Since it is a big security risk here interpolating input from
    ## our incoming params, I will refactor this to have more direct control
    ## of what method we are using for our AR call. To try and keep some
    ## of the model logic out of the controller, I have moved the if/else
    ## statement that decides which order scope to use to the Post model class.
    if %w[asc desc].include?(params[:sort])
      @posts = @posts.order_by(params[:sort])
    end

    ## Since this is only for an HTML mime type we do not necessarily
    ## need the respond_to.
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    ## We can remove the 2nd instance variable since we have the relation
    ## specified for Posts in our User model.
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
      ## Before this simply outputted the user's entire information in JSON
      ## format. I think to better reflect what this action does in its HTML
      ## view, I have refactored it just to include the user's id and name,
      ## excluding information such as the password_digest field. It also
      ## includes the user's posts to also reflect what the HTML view gives.

      ## I would normally use a serializer for this purpose to give even
      ## greater control, but did not feel the need for that in this challenge.
      format.json do
        render json: { id: @user.id, name: @user.name, posts: @user.posts }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<h1>Comments on <%= link_to @post.title, post_path(@post) %></h1>

<ul>
<% @post.comments.each do |comment| %>
  <li>
    <%= comment.body %><br />
    - <%= link_to comment.user_name, user_path(comment.user)%>
  </li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggerPockets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div>
  Sort by: <%= link_to "Newest first", posts_path(sort: :desc) %> | <%= link_to 'Oldest first', posts_path(sort: :asc) %>
</div>

<% @posts.each do |post| %>
  <main>
    <h2><%= link_to post.title, post_path(post) %></h2>

    <p>Posted by: <%= link_to post.user_name, user_path(post.user) %>, <%= time_ago_in_words post.created_at %> ago</p>
    <p><%= post.body %></p>
    <hr />
  </main>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Posted by: <%= link_to @post.user_name, user_path(@post.user) %></p>
<p><%= @post.body %></p>

<%= link_to "View comments", post_comments_path(@post) %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= link_to "View as JSON", user_path(@user, format: 'json') %></p>

<ul>
  <% @user.posts.each do |post| %>
  <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>